/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFrequenciaRouteImport } from './routes/_authenticated/frequencia'

const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFrequenciaRoute = AuthenticatedFrequenciaRouteImport.update({
  id: '/_authenticated/frequencia',
  path: '/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frequencia': typeof AuthenticatedFrequenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/frequencia': typeof AuthenticatedFrequenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/frequencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/frequencia'
  id: '__root__' | '/_authenticated/dashboard' | '/_authenticated/frequencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFrequenciaRoute: typeof AuthenticatedFrequenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/frequencia': {
      id: '/_authenticated/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof AuthenticatedFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFrequenciaRoute: AuthenticatedFrequenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
